GUI
LilliThomas/SoftwareDesign pull request #10
Opened 2024-05-17 04:09 UTC by LilliThomas

new Gui

2024-05-17 16:24 UTC, Resi-r commented
Kannst du noch das kleine Textfeld über dem Eingabefeld hinzufügen?

2024-05-17 16:26 UTC, Resi-r requested changes

2024-05-17 16:26 UTC, Resi-r commented on src/main/java/view/TaschenrecherGUI.java
> +    JButton plus = new JButton("+");
Bitte einheitliche Namen, also auch hier "btnPlus". Und die Namen komplett in Englisch, sonst haben wir da so einen Mischmasch drinne

2024-05-17 16:26 UTC, Resi-r commented on src/main/java/view/TaschenrecherGUI.java
> +        add(textArea, BorderLayout.NORTH);
das Textfeld über dem größeren Eingabefeld fehlt auch noch

2024-05-17 16:26 UTC, Resi-r commented on src/main/java/view/TaschenrecherGUI.java
> +        btn1.addActionListener(listener);
Das zusammen finde ich gut, dann können wir da Code zusammenfassen (sparen)

2024-05-19 16:19 UTC, LilliThomas commented
> Kannst du noch das kleine Textfeld über dem Eingabefeld hinzufügen?

2024-05-19 16:19 UTC, closed without merging