Frontendtest
LilliThomas/SoftwareDesign pull request #17
Opened 2024-05-28 17:42 UTC by LilliThomas

2024-05-28 20:56 UTC, Resi-r requested changes
Kannst du bitte die GUI in "CalculatorView" umbenennen, und die Merge-Konflikte lösen

2024-05-29 08:22 UTC, LilliThomas commented
> Kannst du bitte die GUI in "CalculatorView" umbenennen, und die Merge-Konflikte lösen

ist erledigt

2024-05-29 11:37 UTC, Resi-r requested changes

2024-05-29 11:37 UTC, Resi-r commented on pom.xml
> -            <plugin>
warum hast du pmd rausgenommen?

2024-05-29 12:23 UTC, LilliThomas commented on pom.xml
> -            <plugin>
Habe eigentlich nicht. kann aber sein das das beim mergen passiert ist. ich ergänze es wieder

2024-05-29 12:42 UTC, LilliThomas commented on pom.xml
> -            <plugin>
ist erledigt

2024-05-29 14:45 UTC, closed without merging