dev added model (erster entwurf)
LilliThomas/SoftwareDesign pull request #6
Opened 2024-04-24 10:53 UTC by Resi-r

2024-04-26 14:31 UTC, RikiiB requested changes

2024-04-26 14:31 UTC, RikiiB commented on src/main/java/model/DivisionException.java
vielleicht ein extra Ordner für Exceptions erstellen?

2024-04-26 14:31 UTC, RikiiB commented on src/main/java/model/TaschenrechnerModel.java
> +    private float divide(Operation operation) {
double verwenden

2024-05-06 08:27 UTC, Resi-r commented on src/main/java/model/DivisionException.java
gemacht

2024-05-06 08:28 UTC, Resi-r commented on src/main/java/model/TaschenrechnerModel.java
> +    private float divide(Operation operation) {
gemacht

2024-05-06 08:30 UTC, RikiiB approved these changes

2024-05-06 09:07 UTC, merged