GUI
LilliThomas/SoftwareDesign pull request #7
Opened 2024-04-26 06:31 UTC by LilliThomas

GUI, Methoden müssen noch gefüllt werden

2024-04-26 13:04 UTC, Resi-r requested changes

2024-04-26 13:04 UTC, Resi-r commented on src/main/java/TaschenrecherGUI.java
> +        a3Button.addActionListener(new ActionListener() {
Vlt. kann man hier sprechendere Namen finden (anstatt a3 oder a9)

2024-04-26 13:18 UTC, LilliThomas commented on src/main/java/TaschenrecherGUI.java
> +        a3Button.addActionListener(new ActionListener() {
ist halt butten für die Zahl drei. der rest hat sprechendere NAmen. die Ziffernbolcke heißen alle a1 bis a9button

2024-04-26 14:47 UTC, Resi-r approved these changes

2024-05-06 08:24 UTC, RikiiB commented on src/main/java/TaschenrecherGUI.java
> +        a3Button.addActionListener(new ActionListener() {
und wofür steht das "a"?

2024-05-07 18:14 UTC, merged